export  default {
    menuList : [
        {menuId:1,menuName:'人员管理',icon:'el-icon-s-custom',childMenu:[
            {menuId:11,menuName:'人员信息',path:'/employee/baseInfo',childMenu:[]},
            {menuId:12,menuName:'工作单位',path:'/employee/baseInfo',childMenu:[]},
            {menuId:13,menuName:'类别信息',path:'/employee/typeInfo',childMenu:[]},
        ]},
        {menuId:2,menuName:'车辆管理',icon:'el-icon-truck',childMenu:[
            {menuId:21,menuName:'车辆信息',path:'/vehicle/vehicleInfo',childMenu:[]},
            {menuId:21,menuName:'出入记录',path:'/vehicle/vehicleOutIn',childMenu:[]}
        ]},
        {menuId:3,menuName:'门禁管理',icon:'el-icon-location',childMenu:[
            {menuId:31,menuName:'权限配置',path:'/entrance/jurisdictionSet',childMenu:[]},
            {menuId:32,menuName:'分组管理',path:'/entrance/groupManage',childMenu:[]},
            {menuId:33,menuName:'策略管理',path:'/entrance/strategyManage',childMenu:[]},
            {menuId:36,menuName:'人员出入查询',path:'/entrance/employeeOutIn',childMenu:[]},
        ]},
        {menuId:4,menuName:'访客管理',icon:'el-icon-s-promotion',childMenu:[
                {menuId:41,menuName:'访客预约',path:'/visitor/visitorSubscribe',childMenu:[]},
                {menuId:42,menuName:'来访记录',path:'/visitor/visitorRecord',childMenu:[]}
            ]}
    ],

    tableData:[
        {
            name:'肖红',
            gender:'女',
            organization:'默认组织/一号院',
            papersType:'身份证',
            papersNum:'43042*******220108',
            workNum:'88888888',
            mobile:'18545254566',
            speck:'xiaohong'
        },
        {
            name:'肖红',
            gender:'女',
            organization:'默认组织/一号院',
            papersType:'身份证',
            papersNum:'43042*******220108',
            workNum:'88888888',
            mobile:'18545254566',
            speck:'xiaohong'
        },
        {
            name:'肖红',
            gender:'女',
            organization:'默认组织/一号院',
            papersType:'身份证',
            papersNum:'43042*******220108',
            workNum:'88888888',
            mobile:'18545254566',
            speck:'xiaohong'
        },
        {
            name:'肖红',
            gender:'女',
            organization:'默认组织/一号院',
            papersType:'身份证',
            papersNum:'43042*******220108',
            workNum:'88888888',
            mobile:'18545254566',
            speck:'xiaohong'
        },
        {
            name:'肖红',
            gender:'女',
            organization:'默认组织/一号院',
            papersType:'身份证',
            papersNum:'43042*******220108',
            workNum:'88888888',
            mobile:'18545254566',
            speck:'xiaohong'
        },
        {
            name:'肖红',
            gender:'女',
            organization:'默认组织/一号院',
            papersType:'身份证',
            papersNum:'43042*******220108',
            workNum:'88888888',
            mobile:'18545254566',
            speck:'xiaohong'
        }
    ],

    //性别字典
    genderType:[{label:'男',value:'1'},{label:'女',value:'2'}],
    outInType:[{label:'出',value:'1'},{label:'入',value:'2'}],


}